name: Sync from upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次，时间为UTC 00:00
  workflow_dispatch:  # 手动触发

jobs:
  update-dockerinstall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Backup workflows
      run: |
        mkdir -p backup_github_workflows
        cp -r .github/workflows/* backup_github_workflows/ || true  # 备份工作流文件夹

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/jaywcjlove/reference.git
        git fetch upstream  # 获取上游仓库的最新内容

    - name: Sync with upstream
      run: |
        git checkout main  # 切换到 main 分支
        git reset --hard upstream/main  # 重置本地仓库为上游的 main 分支

    - name: Restore workflows
      run: |
        cp -r backup_github_workflows/* .github/workflows/ || true  # 恢复工作流文件夹
        rm -rf backup_github_workflows  # 删除临时备份文件夹

    - name: Push changes
      run: |
        git add .  # 添加更改
        git commit -m "Sync with upstream and restore workflows"
        git push origin main --force  # 强制推送到你的远程仓库

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
